### ISSUE TITLE
Support for input

### ISSUE THREAD

**Issue by coderGtm** [DulLabs/bhai-lang#99] opened 2022-03-13 17:16 UTC
Can we use this for input?
`bhai sun variable`

**Comment by impratik7** [comment] 2022-03-13 17:19
Great! Looks good.

**Comment by ranupratapsingh** [comment] 2022-03-14 05:50
duplicate of #75

**Comment by ZeroCoolHacker** [comment] 2022-03-18 10:01
actually sun bhai looks better

**Comment by coderGtm** [comment] 2022-03-18 12:15
`Bhai sun var` sounds more programatic though

**Comment by aniketsingh0104** [comment] 2022-03-19 17:18
No current plans to add this feature in this language as this will lead to more complexities in this toy language.

**Closed as completed by aniketsingh0104** 2022-03-19 17:18 UTC
