### ISSUE TITLE
docs if any?

### ISSUE THREAD

**Issue by maheswarantp** [DulLabs/bhai-lang#66] opened 2022-03-12 15:40 UTC
Any docs for this if provided will be helpful. Also, do mention planned features so as to contribute if possible in some way

**Comment by aniketsingh0104** [comment] 2022-03-12 16:07
If you want docs around usage then you can find it here in the readme - https://github.com/DulLabs/bhai-lang#documentation and also in website https://bhailang.js.org/ . 

However, if you want docs around the code of the language itself, then I think the code is pretty self-explanatory. Go through the code once, and you'll probably understand if you have basic understanding of parser & interpreter. 

We don't have any planned features as of now, but contributions are always welcome. Thanks.

**Comment by aniketsingh0104** [comment] 2022-03-19 17:25
Duplicate of - https://github.com/DulLabs/bhai-lang/issues/70

**Closed as completed by aniketsingh0104** 2022-03-19 17:25 UTC
Labels: documentation
