### ISSUE TITLE
Feat : Ability to copy code on clicking  

### ISSUE THREAD

**Issue by Abhijay007** [DulLabs/bhai-lang#102] opened 2022-03-13 18:13 UTC
### Description

Description: Currently in the documentation examples on-site and in the playground as well we don't have the ability to copy on click, 

Proposed solution: to resolve this we can add a new button at the side of pre-existing buttons like "run" and "clear" named "copy" that will help users to copy the code of the playground that he/she wrote, and for examples in documentation, we can use the similar functionality that we use for GitHub or most other documentation sites that placing a small icon at the markdown example and by clicking on that icon show "copied on clipboard" .

![image](https://user-images.githubusercontent.com/64387054/158073263-f1bda985-098e-43b1-afd6-eae819acfc88.png)

### Domain

UI/UX

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by arbhatta-blk** [comment] 2022-03-13 18:21
Duplicate of https://github.com/DulLabs/bhai-lang/issues/84#issue-1167556526 it seems.

**Comment by Abhijay007** [comment] 2022-03-13 18:27
> Duplicate of [#84 (comment)](https://github.com/DulLabs/bhai-lang/issues/84#issue-1167556526) it seems.

@arbhatta-blk thanks buddy for letting me know I forget to check other issues 😅 but it also includes the feat for the playground so can we keep it or do it need to close this issue?

cc : @ankitchouhan1020

**Comment by ankitchouhan1020** [comment] 2022-03-14 04:27
Hi @Abhijay007, @shubh0107 is working on it. Let's wait for his PR. Playground code copy can be done in the same PR. Let's close it for now. Feel free to reopen if you feel for more changes.

**Closed as completed by ankitchouhan1020** 2022-03-14 04:27 UTC
